### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by martinym** [TenSoja/clear-cache#1]
I'm using Firefox ESR 52.4.1 and the FF Add-on Manager says update 3.1 is available for the Clear Cache, but when it tries to install it there's some kind of problem with the download -- it doesn't say what it is exactly. See attached screenshot.
![clear_cache_update_isue](https://user-images.githubusercontent.com/2790408/31516097-27d44962-af4c-11e7-8a69-539a7d25dc13.png)

**Comment by TenSoja** [comment]
@martinym  sorry for the delay in answering. I couldn't reproduce the error. Does the problem persist for you?

**Comment by martinym** [comment]
Yes, it still persists. I didn't notice this message until now (since I don't log in to github very often), and have just submitted a new problem report about the issue.  I'm now using using Firefox ESR 52.7.3 (64-bit) on Windows and the installed version I have of Clear Cache is 0.9.3.

Below is a screenshot of the (very generic) error message.

![clear-cache-update-error-message](https://user-images.githubusercontent.com/2790408/38109521-4507f562-334d-11e8-9f7e-f1ac61f7531c.jpg)

The problem maybe a conflict with one of the many other extensions I have installed, but none of them have anything to do with the caches, so I have no idea which one it could be...

**Comment by ksuuk** [comment]
I have same problem, Centos x64, FF say's that the add-on is corrupt.
![screenshot_5](https://user-images.githubusercontent.com/26193002/42631895-2e2825c6-85e4-11e8-9d13-5453a5a3fc60.png)

![screenshot_6](https://user-images.githubusercontent.com/26193002/42631905-32f725de-85e4-11e8-9719-71a012372de7.png)

**Comment by TenSoja** [comment]
I remember that at the time I tested and was unable to reproduce the problem, after that I contacted mozzila, I will leave it open to check if this problem will occur in a new version.
