### ISSUE TITLE
Icon problem

### ISSUE THREAD

**Issue by Uh-Clem** [TenSoja/clear-cache#1]
I just restarted Firefox (55.0.3) on a Macbook Pro (OS 10.11) and suddenly the Clear Cache icon is causing the toolbar to take up half the screen.  Disabling Clear Cache returns everything to its proper perspective.  I see that the tool was updated today.  Methinks this is a problem.  Here's what it looks like:

![screen shot 2017-09-13 at 12 54 06 pm](https://user-images.githubusercontent.com/18448172/30397739-b06284d2-9882-11e7-8ae9-72599f1c9a86.jpg)

**Comment by TenSoja** [comment]
I was not able to reproduce the error, Im with version 55.0.3 of FF and using OSX 10.12.6. 
After closing and opening FF, does the problem continue?
It may be a cache problem (lol)
If it persists I think I'll stop using svg and use png instead.

**Comment by Uh-Clem** [comment]
Michel,  Thanks for getting back so quickly.  This continues to be a problem for me after several restarts and clearing cache.  If, as it appears, no one else is reporting the problem, I suspect it is the result of some combination of the extensions I'm using.  When I have some free time I'll try to narrow it down to see what might be causing this.
 

Sent: Thursday, September 14, 2017 at 7:13 AM

**Comment by Uh-Clem** [comment]
Michel, I've narrowed the problem to a conflict/interaction between Clear Cache and an extension called Noia Buttons which substitutes a set of icons for the standard Firefox-issued ones.  Why this should suddenly become a problem or why it is only your icon that is affected, I haven't got a clue but there it is.

**Comment by wmdiabel** [comment]
icon problem persists for FF 56  beta 11 and 12. Monster size sweeping brush.
