### ISSUE TITLE
Add option to clear Cookies too for current page.

### ISSUE THREAD

**Issue by Edgaras91** [TenSoja/clear-cache#11]
Hi, I could not find any other extension that clears cache just for current page. I would love to use F9 to clear both, cookies and cache.
I understand that it's in the name: "clear-cache", but this optional (defaulting to false) feature would make all the difference for me, else I would need to use some other extension (that I could not find) in addition to this.

To be more specific, if I am on localhost:44339, I want to press F9, and both Cache and Cookies to be deleted from the current page:
![image](https://user-images.githubusercontent.com/32236075/217287991-d3c5a2a4-9dd0-476d-b501-9a87456fce50.png)

**Comment by TenSoja** [comment]
Hi,
The option to clear cookies will be in the next version under development

**Comment by TenSoja** [comment]
All new cleaning options:

Downloads
Passwords
History
Plugin data
Form data
Cookies
Service workers
