### ISSUE TITLE
rows have slipped in settings

### ISSUE THREAD

**Issue by HJMeyer** [TenSoja/clear-cache#14]
The rows have slipped in the settings. Hard to click the right preferences. (screenshot attached)

![Screenshot 2024-09-01 120651](https://github.com/user-attachments/assets/e93a9093-f13a-4c38-88ea-87acf2a10a37)

**Comment by TenSoja** [comment]
Fixed in new version 4.1

**Comment by TenSoja** [comment]
Fixed in new version 4.1
