### ISSUE TITLE
HOSTS file is ignored

### ISSUE THREAD

**Issue by David263** [TenSoja/clear-cache#3]
This addon only clears the standard caches reported by about:cache! The HOSTS file is still hidden by some hidden cache in Firefox. Refreshing a web page does not use HOSTS to fetch from the correct IP address. I clicked the icon, since I use F9 for another purpose. Firefox 56.0.2 (32-bit).

Note that Chrome always respects the HOSTS file.

**Comment by TenSoja** [comment]
Hi @David263 ,

Clear Cache really only does what you can for about:cache but does it in a more practical way.
But in the light of your problem, there is a known problem with Firefox and the HOSTS file reported here: https://support.mozilla.org/en-US/questions/1117449
