### ISSUE TITLE
Notification stopped notifying

### ISSUE THREAD

**Issue by iansebryk** [TenSoja/clear-cache#4]
used to get a toast telling me the cache has been cleared.  it doesn't do that anymore, despite clearing and resetting the option to do so.  is there something i could be missing?  while it may seem small, since i'm clearing the caches often (webDev) it's something that i've come to rely on to know if it actually HAS been cleared or not.  nothing has changed lately other than the *removal* of a couple useless addons...

**Comment by TenSoja** [comment]
What is your environment?
I simulated here there was no failure, could it be a conflict with the Toggle Reader Mode shortcut?

**Comment by TenSoja** [comment]
I tested the feature on both the previous version and version 4.1, and the notifications are appearing as expected. Since the test conditions were not provided, I will proceed to close the issue
