### ISSUE TITLE
The clear cache button doesn't clear all of the cache

### ISSUE THREAD

**Issue by houtanb** [TenSoja/clear-cache#5]
It seems as though it clears a lot of cache but not everything. Most recently, upon pushing the button, I am left with 48KB of cookies and 1.2MB of data. If you do not want to clear everything by default, can you provide a setting option that we can activate to allow us to clear everything?

Basically, I viewed this browser add-on as a shortcut for going to `Settings->Privacy & Security-> Clear Data...->Clear`. Is it not supposed to be that?

**Comment by RevRagnarok** [comment]
All it does is call `chrome.browsingData.removeCache()` - I had just checked the source earlier because I wanted to ensure it _wasn't_ clearing any cookies, etc...

https://developer.chrome.com/docs/extensions/reference/browsingData/#method-removeCache

**Comment by PatrickRoesler** [comment]
I can confirm that. If I'm logged into my software project and clear the cache, I should be logged out. This plugin reports "Cache cleared", but I'm still logged in. So it is not working properly.

**Comment by TenSoja** [comment]
> All it does is call `chrome.browsingData.removeCache()` - I had just checked the source earlier because I wanted to ensure it _wasn't_ clearing any cookies, etc...
> 
> https://developer.chrome.com/docs/extensions/reference/browsingData/#method-removeCache

Exactly, it only makes the API cache clearing call
