### ISSUE TITLE
Conflicts with the "Toggle Reader Mode"  shortcut

### ISSUE THREAD

**Issue by azumukupoe** [TenSoja/clear-cache#7]
> Toggle Reader Mode | F9

https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

**Comment by TrueXakeP** [comment]
You can manage addons hotkeys from "Tools for all add-ons" menu with a gear-iconed button in Firefox addon manager.
https://www.mrfdev.com/manage-extension-shortcuts

Sorry for my english.
